// actions/types.js
export const SET_SIGNUP_INFO = 'SET_SIGNUP_INFO';
export const SET_SIGNUP_STEP2_INFO = 'SET_SIGNUP_STEP2_INFO';



export const RESET_SIGNUP_INFO = 'RESET_SIGNUP_INFO';
export const RESET_SIGNUP_STEP2_INFO = 'RESET_SIGNUP_STEP2_INFO';


export const SET_UNAUTHORIZED_INFO = 'SET_UNAUTHORIZED_INFO';